### ISSUE TITLE
with v0.3 mode-line still showing when using top position

### ISSUE THREAD

**Issue by hans-d** [rougier/nano-modeline#24]
I'm using anno-modeline with posotion top. On v0.2, the (bottom) mode-line was nicely hidden.

On v0.3 however, the mode-line is still showing.
- mode-line is set to nil
- colors used are from mode-line, checked that by modifying face and not seeing that reflected in any other face / did update the modeline colors

So far, not been able to hunt down this in the code changes

**Comment by hans-d** [comment]
casued by `(add-hook 'window-configuration-change-hook #'nano-modeline-update-windows)`

On removing the hook, all was ok.

**Comment by hans-d** [comment]
seems to be this one: `(one-window-p t)`
- one one window, it shows the modeline
- ona a frame with two windows, split with `C-x 2`, when the top window is active it shows in both, when the bottom window is active it is hidden

**Comment by hans-d** [comment]
current workaround: add `(remove-hook 'window-configuration-change-hook #'nano-modeline-update-windows)` after require - until investigated / fixed

**Comment by aaronjensen** [comment]
Also:

```
(setq no-mode-line t)
```

That's a built-in work-around AFIACT and it's what I do now.

The reason it is as it is is that it expects [a face to be applied to the `mode-line` to constraint its height](https://github.com/rougier/nano-emacs/blob/70993ff7018850b56fd0e87b83b44ace6f6e67df/nano-theme.el#L134-L156). This is what gives the gray line above the echo area in screenshots of nano.

Of note is that this is not mentioned in the README or is it present in `nano-theme`. I only know about it because I used to use parts of `nano-emacs`.

The current function to determine whether or not to render it is problematic as well when you have a buffer that is in more than one window. It gets confused.

**Comment by artelse** [comment]
I'm having the same problem; i.e. a dark empty mode-line at the bottom and normal one at the top. Strangely enough, when I set the `nano-modeline-position` to `bottom` is shows it at the top and vice versa. After fiddling with top/ bottom, the bottom bar will disappear and top bar is shown, however with a `bottom` positioning setting.

**Comment by Airwan** [comment]
Hi,

 line 784  replacing `setq mode-line-format` by `setq header-line-format` do the job. Should it have a test which set the correct value depending on `nano-modeline -position` ?

**Comment by rougier** [comment]
I wanted to have a single line separating the minibuffer from all the windows and this is the reason for the hook that show a 1 pixel height modeline for the bottom window and no modeline for other windows. It is far from perfect as you noticed but I did not find a proper way to do it. Ideally, minibuffer should be in charge of displaying this line but I think it is not really possible.

**Comment by rougier** [comment]
Maybe I'll disable it until I find a proper solution.

**Comment by rougier** [comment]
Fixed with the new [simpler](https://github.com/rougier/nano-modeline/tree/simpler) branch.
