### ISSUE TITLE
Showing obvious/boring information

### ISSUE THREAD

**Issue by DamienCassou** [rougier/nano-modeline#33]
I'm wondering if nano-modeline should show what I would consider obvious/boring information or if it should display nothing. Examples of what I would consider obvious/boring:

- "RW" (for read-write status): when in a file-visiting buffer, chances are very high that the buffer can be written.
- "RO" (for read-only status): when in a non-file-visiting buffer, this is always the case that the buffer is read-only.

Information I would really appreciate seeing: "RO" in a file-visiting buffer that is read-only. This is rare and important information. The other cases are obvious and don't deserve my attention.

**Comment by rougier** [comment]
The `RW` is mostly useful when it becomes `**` to signal file has been modified. We could keep only the `**` but it will "disrupts" the modeline. Also, spaces before/after prefix are used to enlarge the modeline. Nonetheless, I agree with your analysis and there may be a better way to be find.

**Comment by DamienCassou** [comment]
> We could keep only the `**`

this is my point indeed.

> it will "disrupts" the modeline

Do you mean that the "name" and "primary" parts would move left each time the user saves? Is that a problem?

What about only using the face to convey the information:

- a "warning" face would be used when a file is modified or when a file is read-only
- a "normal" face would be used in other cases (saved file or not a file)

Then we don't need any text (except a few spaces to apply the face on) and no disruption occurs.

**Comment by rougier** [comment]
I've just pushed a "no-prefix" experimental branch.

**Comment by aaronjensen** [comment]
I think this direction is reasonable, though not as aesthetically pleasing. I'm OK with that though. One could add the bar of color to the left a la doom/mood-line if one wanted that.

There are a few things that I'm doing on my fork that may be worth doing on the main line. This is modified from `no-prefix`, it's the final `concat` in `nano-modeline-render`:

```
(concat
       (propertize " "  'face face-secondary 'display `(space :width left-fringe))
       left
       (propertize " "  'face face-secondary 'display `(raise ,nano-modeline-space-top))
       (propertize " "  'face face-secondary 'display `(raise ,nano-modeline-space-bottom))
       (propertize " "  'face face-secondary 'display `(space :align-to (- right-fringe ,right-len)))
       right)
```

A few things to note:

1. I use a variable pitch font for all my modeline primary faces and a fixed one for  secondary, so I used secondary for everything above, though the only concrete impact that has is that it uses the height of the secondary + the raises rather than the height of the primary (my secondary is a little taller)
2. I put the raises in between the primary and secondary so the size of their space is largely irrelevant. 
3. I use fringe width on both the right and left to pad the mode line. I simplified the `align-to` on the right to something I think is equivalent to what it was w/o the minus 0.

I may play with adding a `*` after the file name to indicate that it is modified (or a round circle as is the VS Code style, especially since `*` is a common in emacs buffer names).

**Comment by DamienCassou** [comment]
I've just started trying the `no-prefix` branch and I have to say I like it. Quick feedback: instead of multiplying the number of faces, can't you combine them? I.e., have `active`, `inactive`, `RW`, `RO` and `modified` faces and use 2 of them?

**Comment by rougier** [comment]
@aaronjensen I also find it less pleasant aesthetically and I end up adding a " ☰ " (not commited) instead of prefix that is clickable to show the mode menu. I never use it but I like the contrast the prefix brings. I will add it as an option. If you add the fringe space in front, that would need to be balanced with a space at the end of the prefix. With such prefix, we can use color to tell buffer is modified but if a user decide to have no prefix, then we need another way. I've played with color for the name but it's not satisfactory.

@DamienCassou I agree that faces could be merged, I'll look into that.

**Comment by aaronjensen** [comment]
@rougier I've gotten used to it without anything on the left but the name of the buffer. I also switched to using a `:box` on the faces, rather than the `display :raise` and  `:space` to give the right shape and size to the header line. This has the benefit of making the size more consistent, but means I can't put a colored bar or something like that on the far left. 

Here's an example:

```el
`(nano-modeline-active               ((,light (:background ,nano-light-background-alt
                                               :box (:line-width (8 . 4) :color ,nano-light-background-alt :style nil)))
                                      (,dark (:background ,nano-dark-background-alt 
                                               :box (:line-width (8 . 4) :color ,nano-dark-background-alt :style nil))))
```

I mention the colored bar because the one current problem I have is it's too hard do differentiate between the active and inactive windows with my theme. Previously I relied on the colored `RW` and I mildly lightened the primary text in the header line. I'll keep playing with it.

**Comment by rougier** [comment]
Gorgeous. I just discovered box are now configurable in H/V direction which is great. This is precisely what I was trying to achieve with the up/down spaces. I also like the smaller size of primary information. Ideally, right part could also beneficiate from a reduced size but it messes up with the align method. By the way, is is the tabbar above?

**Comment by aaronjensen** [comment]
As long as the align has the same face as the right and it is a fixed pitch face the align should work. I use this:

```el
(propertize " "  'face face-secondary 'display `(space :align-to (- right-fringe ,right-len)))
```

And yes, that's the tab bar with [this theme](https://github.com/aaronjensen/nano-theme/blob/master/nano-theme.el#L782-L793)

**Comment by rougier** [comment]
Thanks I've made the modification for the space / align-to. I've also added an option for the prefix such that user can now choose to have the default RO/RW/** prefix, no prefix or an icon that is sutomizable for each mode (I still need to modify the custom type for allowing cusomization but I'm a bit stuck with the syntax)

**Comment by aaronjensen** [comment]
On the spacing, did you find you had to do `,(- right-len 0)` vs `,right-len`? I don't understand what the `- 0` is for.

The icons are an interesting idea. Can you share a screenshot of some of them? I don't have patched fonts installed.

**Comment by aaronjensen** [comment]
Here's where I am now. I left enough space between the name and the primary so that the modified bullet can appear w/o shifting anything. 

<img width="938" alt="CleanShot 2022-04-08 at 06 25 53@2x" src="https://user-images.githubusercontent.com/8588/162417843-362eb137-870f-4840-b4f6-6b7f24ec1fc0.png">

**Comment by rougier** [comment]
The 0 come from a debug session, I just forgot to remove it. Extra spaces might be a good idea indeed.

<img width="665" alt="Screenshot 2022-04-08 at 14 30 39" src="https://user-images.githubusercontent.com/327203/162435918-c294f56e-e8aa-4dd2-aec2-341778cfaac1.png">

**Comment by aaronjensen** [comment]
What is the bottom line?

**Comment by rougier** [comment]
Just an underline in the `nano-modeline-active` face (in my config, I did not make it default)

**Comment by DamienCassou** [comment]
```emacs
(defcustom nano-modeline-prefix 'default ...)
```

I don't think the default value should be named `default` because:
- it doesn't say anything about what this value does
- I have never seen any default value with this name
- the source code already makes it clear that this is the default value.

I suggest something like `status` or `file-mode` or similar instead.

**Comment by DamienCassou** [comment]
> Just an underline in the nano-modeline-active face (in my config, I did not make it default)


Setting underline to `t` doesn't have the same impact for me:
![2022-04-10-103620](https://user-images.githubusercontent.com/217543/162609932-1462bd22-73c2-47ee-b96f-73f000200f8d.png)

**Comment by rougier** [comment]
`'status` sounds good. I'll make the cnage.

For the uderline, this should be for the 'nano-modeline-active' (that is inherited) and then you have to disable some settings:
```
(setq x-underline-at-descent-line t)
(setq x-underline-at-descent-line t)
(setq x-use-underline-position-properties nil)
(setq underline-minimum-offset 10)
```

**Comment by mclearc** [comment]
If it's of interest I've incorporated some changes in my fork of nano-modeline that might be of interest. I have made the status symbol configurable, or you can just not display it at all. There are also differences set for GUI vs. TTY. Here's a screenshot of the normal R/W buffer in GUI. 
<img width="776" alt="Screen Shot 2022-04-11 at 19 11 09" src="https://user-images.githubusercontent.com/1502422/162848007-6a493b9c-1cd5-434c-9e9b-2e9dfabcdc57.png">
 
The code is here: https://github.com/Lambda-Emacs/lambda-line

**Comment by rougier** [comment]
Nice. Configuring the RO/RW/** prefixes seem to be a good idea indee. I'll add the option.

**Comment by DamienCassou** [comment]
What is the status of this experimental work?

**Comment by rougier** [comment]
Ready to be merged!

**Comment by DamienCassou** [comment]
You seem to have released 0.7 out of the `no-prefix` branch but this one is not merged into master yet.

**Comment by rougier** [comment]
Oh, I'll fix it.

**Comment by rougier** [comment]
done.
